# Generated by Django 4.2.15 on 2024-11-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_number', models.BinaryField()),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_address_id', models.IntegerField()),
            ],
        ),
    ]
