# Generated by Django 4.2.15 on 2024-11-26 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_contratacion', models.DateField()),
                ('dni', models.CharField(max_length=10)),
                ('direccion', models.ForeignKey(db_column='fk_empleado_direccion_id', on_delete=django.db.models.deletion.CASCADE, to='sucursales.direccion')),
                ('sucursal', models.ForeignKey(db_column='fk_empleado_sucursal_id', on_delete=django.db.models.deletion.CASCADE, to='sucursales.sucursal')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleado',
            },
        ),
    ]
