# Generated by Django 4.2.15 on 2024-11-22 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('tipo_operacion', models.CharField(max_length=50)),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('cuenta_numero', models.ForeignKey(db_column='cuenta_numero', on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuenta')),
            ],
        ),
    ]
