# Generated by Django 4.2.15 on 2024-11-22 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca_tarjeta', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('cvv', models.IntegerField()),
                ('fecha_otorgamiento', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('tipo', models.CharField(max_length=20)),
                ('cliente_id', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('marca_id', models.ForeignKey(db_column='marca_id', on_delete=django.db.models.deletion.CASCADE, to='marca_tarjeta.marcatarjeta')),
            ],
        ),
    ]
