# Generated by Django 4.2.15 on 2024-11-26 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_direccion', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'Direccion',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sucursal', models.CharField(max_length=50)),
                ('direccion_detalle', models.CharField(max_length=255)),
                ('direccion', models.ForeignKey(db_column='fk_sucursal_direccion_id', on_delete=django.db.models.deletion.CASCADE, to='sucursales.direccion')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'Sucursal',
            },
        ),
    ]
