# Generated by Django 4.2.15 on 2024-11-22 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursal', '0001_initial'),
        ('clientes', '0001_initial'),
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('cliente_id', models.ForeignKey(blank=True, db_column='cliente_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('empleado_id', models.ForeignKey(blank=True, db_column='empleado_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
                ('sucursal_id', models.ForeignKey(blank=True, db_column='sucursal_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursal.sucursal')),
            ],
        ),
    ]
